CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 username TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS incidents (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 date TEXT,
 tag TEXT,
 severity TEXT,
 comments TEXT,
 reporter TEXT,
 user_id INTEGER,
 FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 incident_id INTEGER,
 text TEXT
);

CREATE TABLE IF NOT EXISTS tags (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT
);

CREATE TABLE IF NOT EXISTS incident_tags (
 incident_id INTEGER,
 tag_id INTEGER
);